### PR TITLE
Add accordion samples

### LINKED ISSUE #291: Add samples for Accordion component

### PR DESCRIPTION
**Pull request by ddaribo**
Closes #291

1. Overview sample
overview

2. Customizations sample
customization

3. Accordion Nested Scenario sample
nested

### CODE REVIEW

**Comment by mmart1n** [comment]
Categories title disappears when deselecting all categories
accordion_overview_categories

**Comment by mmart1n** [comment]
The time does not appear in the title
accordion_overview_time

**Comment by ddaribo** [comment]
> The time does not appear in the title accordion_overview_time [ accordion_overview_time ](https://user-images.githubusercontent.com/44684385/179499026-8ab8bd12-9c30-4532-9e48-4287377e15af.gif) [ ](https://user-images.githubusercontent.com/44684385/179499026-8ab8bd12-9c30-4532-9e48-4287377e15af.gif)

Refactored, so that the header is updated by handling the `igcChange` event of the `igc-date-time-input`. This updates the text on commiting the entered value.
However, when in/decrementing with the Arrow keys as well as by scrolling, this event is currenlty not fired as logged in https://github.com/IgniteUI/igniteui-webcomponents/issues/440.

**Comment by mmart1n** [comment]
> > The time does not appear in the title accordion_overview_time
> >       
> >         [
> >           
> >             accordion_overview_time
> >           
> >         ](https://user-images.githubusercontent.com/44684385/179499026-8ab8bd12-9c30-4532-9e48-4287377e15af.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/44684385/179499026-8ab8bd12-9c30-4532-9e48-4287377e15af.gif)
> >         
> >        [ accordion_overview_time ](https://user-images.githubusercontent.com/44684385/179499026-8ab8bd12-9c30-4532-9e48-4287377e15af.gif)
> >       
> >         [
> >           
> >             accordion_overview_time
> >           
> >         ](https://user-images.githubusercontent.com/44684385/179499026-8ab8bd12-9c30-4532-9e48-4287377e15af.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/44684385/179499026-8ab8bd12-9c30-4532-9e48-4287377e15af.gif)
> >         
> >        [ ](https://user-images.githubusercontent.com/44684385/179499026-8ab8bd12-9c30-4532-9e48-4287377e15af.gif)
> 
> Refactored, so that the header is updated by handling the `igcChange` event of the `igc-date-time-input`. This updates the text on commiting the entered value. However, when in/decrementing with the Arrow keys as well as by scrolling, this event is currenlty not fired as logged in [IgniteUI/igniteui-webcomponents#440](https://github.com/IgniteUI/igniteui-webcomponents/issues/440).

What about the focus out behavior? Is it going to be reflected by the `igcChange` event as well?
accordion_overview_time_focusout

**Comment by ddaribo** [comment]
> 



> > > The time does not appear in the title accordion_overview_time
> > >       
> > >         [
> > >           
> > >             accordion_overview_time
> > >           
> > >         ](https://user-images.githubusercontent.com/44684385/179499026-8ab8bd12-9c30-4532-9e48-4287377e15af.gif)
> > >         
> > >         
> > >           
> > >             
> > >               
> > >             
> > >             
> > >               
> > >               
> > >             
> > >           
> > >           [
> > >             
> > >               
> > >             
> > >           ](https://user-images.githubusercontent.com/44684385/179499026-8ab8bd12-9c30-4532-9e48-4287377e15af.gif)
> > >         
> > >       
> > > ```
> > >     [
> > >       
> > >         accordion_overview_time
> > >       
> > >     ](https://user-images.githubusercontent.com/44684385/179499026-8ab8bd12-9c30-4532-9e48-4287377e15af.gif)
> > >     
> > >     
> > >       
> > >         
> > >           
> > >         
> > >         
> > >           
> > >           
> > >         
> > >       
> > >       [
> > >         
> > >           
> > >         
> > >       ](https://user-images.githubusercontent.com/44684385/179499026-8ab8bd12-9c30-4532-9e48-4287377e15af.gif)
> > >     
> > >    [ accordion_overview_time ](https://user-images.githubusercontent.com/44684385/179499026-8ab8bd12-9c30-4532-9e48-4287377e15af.gif)
> > >   
> > >     [
> > >       
> > >         accordion_overview_time
> > >       
> > >     ](https://user-images.githubusercontent.com/44684385/179499026-8ab8bd12-9c30-4532-9e48-4287377e15af.gif)
> > >     
> > >     
> > >       
> > >         
> > >           
> > >         
> > >         
> > >           
> > >           
> > >         
> > >       
> > >       [
> > >         
> > >           
> > >         
> > >       ](https://user-images.githubusercontent.com/44684385/179499026-8ab8bd12-9c30-4532-9e48-4287377e15af.gif)
> > >     
> > >    [ ](https://user-images.githubusercontent.com/44684385/179499026-8ab8bd12-9c30-4532-9e48-4287377e15af.gif)
> > > ```
> > 
> > 
> > Refactored, so that the header is updated by handling the `igcChange` event of the `igc-date-time-input`. This updates the text on commiting the entered value. However, when in/decrementing with the Arrow keys as well as by scrolling, this event is currenlty not fired as logged in [IgniteUI/igniteui-webcomponents#440](https://github.com/IgniteUI/igniteui-webcomponents/issues/440).
> 
> What about the focus out behavior? Is it going to be reflected by the `igcChange` event as well? accordion_overview_time_focusout [ accordion_overview_time_focusout ](https://user-images.githubusercontent.com/44684385/179717361-ee1fd3e1-f576-4951-9205-0e9c168dce6a.gif) [ ](https://user-images.githubusercontent.com/44684385/179717361-ee1fd3e1-f576-4951-9205-0e9c168dce6a.gif)

The logged [issue](https://github.com/IgniteUI/igniteui-webcomponents/issues/440) addresses all questions regarding the `igc-date-time-input` events.
Meanwhile, we can still use the `igcChange` event to update the "Time" label on commiting the value (i.e. focus out of the input).

**Review by HUSSAR-mtrela — APPROVED** [review]

**Pull request merged**
