### PR TITLE
refactor(*): moving the working dir to root

### PR DESCRIPTION
**Pull request by kdinev**
Also

 - Upgrading the project to use webpack 5
 - Upgrading all plugin dependencies
 - Reenabling node 18 build now that webpack 5 is used
 - Making the working directory be root with the intention to use a single dependencies folder.

### CODE REVIEW

**Review by HUSSAR-mtrela — CHANGES_REQUESTED** [review]
I reviewed this PR and some changes are required

**Review by HUSSAR-mtrela — CHANGES_REQUESTED** [review]
please undo moving package.json and tsconfig files back to the browser folder

**Comment by kdinev** [comment]
@HUSSAR-mtrela My intention is to have a single `package.json` and a package-lock, which is used for the full samples app, as well as for individual samples. This way the local repo would not be polluted with multiple `node_modules` folders and in a sense would be cleaner. The whole idea behind a mono-repo is to reuse the same dependencies folder for all subprojects.

**Comment by gmurray81** [comment]
@HUSSAR-mtrela , @kdinev and I talked about why the individual package.jsons are important.

I think we should kill yarn though, if possible, unless there is some reason it was important?

**Comment by kdinev** [comment]
Btw, all of the dependabot PRs will get closed automatically after the merge of this PR and a dependabot rebase on top of the latest vnext.

**Review by gmurray81 — APPROVED** [review]

**Review by HUSSAR-mtrela — APPROVED** [review]

**Pull request merged**
