### PR TITLE
chore(*): Get dom elements on demand after load.

### LINKED ISSUE #834: PivotGrid state persistence samples throws error on save.
Run sample at: https://staging.infragistics.com/webcomponents-demos/grids/pivot-grid/state-persistence-main
Hit Save button.

Error is thrown: 

Cannot read properties of null (reading 'getStateAsString')
    at D.saveGridState (65353.ed944853.chunk.js:2:88508)

Same happens for the noop state persist sample at: https://staging.infragistics.com/webcomponents-demos/grids/pivot-grid/data-persistence-noop

### PR DESCRIPTION
**Pull request by MayaKirova**
Closes #834

### CODE REVIEW

**Comment by MarielaTihova** [comment]
Issue 1: When running all the samples, going to pivot-grid/data-persistence-noop sample error message is shown in console

WC PivotGrid Error on load (all samples)

**Comment by MarielaTihova** [comment]
> Issue 2: When running all the samples, going to pivot-grid/state-persistence-main sample and clicking on "Restore" error messages are shown in console
> 
> WC PivotGrid Error on Reload (all samples)

Marking PR as verified, as this is related to unexpected user behaviour and is a minor issue. 
@MayaKirova would you please raise this as an issue with low priority?

**Comment by MayaKirova** [comment]
> > Issue 2: When running all the samples, going to pivot-grid/state-persistence-main sample and clicking on "Restore" error messages are shown in console
> > WC PivotGrid Error on Reload (all samples)
> 
> Marking PR as verified, as this is related to unexpected user behaviour and is a minor issue. @MayaKirova would you please raise this as an issue with low priority?

@MarielaTihova Sure. But I was unable to reproduce it with the provided steps. Could you re-check if this still reproduces for you? If so could you provide more details, such as what state is being restored for the grid?

**Comment by MarielaTihova** [comment]
All issues are either resolved or can't reproduce anymore.

**Pull request merged**
